# set initial configurations for git pod 
#check this https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: aws-cli
    env:
      aws_CLI_AUTO_PROMPT: on-partial
    init: |
      cd / workspace
vscode:
  extensions:
    - 42Crunch.vscode-openapi
